version: "3"
volumes:
  data:
services:
  postgres:
    container_name: nextjs_postgres
    image: "postgres:latest"
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DBNAME}
    ports:
      - 5433:5432
      - 5555:5555
    volumes:
      - data:/var/lib/postgresql
    networks:
      - my-network
  file_storage:
    container_name: nextjs_file_storage
    image: "minio/minio"
    restart: always
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - 9000:9000
    volumes:
      - data:/data
    networks:
      - my-network

  app:
    depends_on:
      - postgres
    container_name: nextjs-app
    build:
      context: .
      dockerfile: dev.Dockerfile

    environment:
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=${DATABASE_URL}
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    networks:
      - my-network

networks:
  my-network:
    external: true
