version: '3'
volumes:
  data:
services:
  task_postgres:
    container_name: task_postgres
    image: 'postgres:latest'
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DBNAME}
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql

  task-minio:
    container_name: task-minio
    image: quay.io/minio/minio
    restart: always
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ~/minio/data:/data
    command: server /data --console-address ":9001"

  task_app:
    depends_on:
      - task_postgres
    container_name: task_app
    restart: always
    command: sh -c "npx prisma migrate dev --name init && npx prisma db seed && npm i tsx -g && npx next build && npx next start -p 5173"
    build:
      context: .
      dockerfile: prod.Dockerfile
    env_file:
      - .env
    ports:
      - 5173:5173
      - 5555:5555
